#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

# Activate VirtualEnv in order to use the correct libraries

echo "--> ACTION HOOK: build <--"
media=$OPENSHIFT_DATA_DIR"media"
if [ ! -d $media ]; then
mkdir $media
fi
ln -sf $media $OPENSHIFT_REPO_DIR/wsgi/static/media
# from http://masci.wordpress.com/2012/07/17/serving-django-media-files-in-openshift/